package GUI;

import javax.swing.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.SimpleDateFormat;

import javax.swing.GroupLayout.Alignment;
import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;

/**
 *
 * @author PC PV
 */
public class ChamCong extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form NewJFrame
     */
    public ChamCong() {
		setTitle("Ch\u1EA5m c\u00F4ng theo th\u00E1ng");
    	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    @SuppressWarnings({ "unchecked", "rawtypes" })
	private void initComponents() {
//        ImageIcon image = new ImageIcon(ClassLoader.getSystemResource("icons/icons/Hotel_Icon.png"));
//        setIconImage(image.getImage());
    	setVisible(true);
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 11));
        
        
        menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        overall = new JMenu("TU\u1EF2 CH\u1ECCN");
        overall.setForeground(Color.BLUE);
        menuBar.add(overall);
        
        back = new JMenuItem("QUAY V\u1EC0 TRANG CH\u1EE6");
        overall.add(back);
        back.setForeground(Color.BLUE);
        back.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
               	new TrangChu();
               	dispose();
            }
        });
        
        exit = new JMenuItem("THO\u00C1T H\u1EC6 TH\u1ED0NG");
        overall.add(exit);
        exit.setForeground(Color.RED);
        exit.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
               	System.exit(0);
            }
        });

    

        jPanel1.setBackground(SystemColor.textHighlight);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("B\u1EA2NG CH\u1EA4M C\u00D4NG THEO TH\u00C1NG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tu\u1EF3 ch\u1ECDn th\u00E1ng"));

        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 11)); // NOI18N
        jLabel1.setText("N\u0103m");

        jButton1.setText("Xem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
         lblTo = new JLabel("Th\u00E1ng");
         lblTo.setFont(new Font("Tahoma", Font.PLAIN, 11));
        
         comboBoxNam = new JComboBox();
         String[] choiceNam = {"2021", "2022", "2023"};
         comboBoxNam = new JComboBox(choiceNam);
         for (i =0 ; i<choiceNam.length ; i++) {
         	if(Integer.parseInt(choiceNam[i]) == dateYearInt) {
         		break;
         	}
         }
         comboBoxNam.setSelectedIndex(i);
         
         
        comboBoxThang = new JComboBox();
        String[] choiceThang = {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"};
        comboBoxThang = new JComboBox(choiceThang);
        for (i =0 ; i<choiceThang.length ; i++) {
        	if(Integer.parseInt(choiceThang[i]) == dateMonthInt) {
        		break;
        	}
        }
        comboBoxThang.setSelectedIndex(i);
              
 
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(lblTo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        			.addGap(23)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButton1)
        				.addComponent(comboBoxThang, Alignment.TRAILING, 0, 105, Short.MAX_VALUE)
        				.addComponent(comboBoxNam, 0, 105, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(comboBoxNam, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblTo)
        				.addComponent(comboBoxThang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jButton1)
        			.addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(329)
        					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(250)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(59)
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(71))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(ActionEvent evt) {
    	try {
    		
    	
        String nam = (String) (comboBoxNam.getSelectedItem());
        String thang = (String) (comboBoxThang.getSelectedItem());
        
        if (nam.equals("") || thang.equals("")) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng m\u1EDF \u0111\u01B0\u1EE3c b\u1EA3ng ch\u1EA5m c\u00F4ng");
        }
        
        else {
        QuanLyChamCong cc = new QuanLyChamCong(nam,thang);
        cc.setVisible(true);
        cc.pack();
        cc.setLocationRelativeTo(null);
        cc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        dispose();
        }
    	}
    	catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng m\u1EDF \u0111\u01B0\u1EE3c b\u1EA3ng ch\u1EA5m co");
            ex.printStackTrace();
    	}
    }



	/**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChamCong().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	SimpleDateFormat formatterYear= new SimpleDateFormat("yyyy");
	SimpleDateFormat formatterMonth= new SimpleDateFormat("MM");
	Date date = new Date(System.currentTimeMillis());
	String dateYear = formatterYear.format(date);
	String dateMonth = formatterMonth.format(date);
	int dateYearInt = Integer.parseInt(dateYear);
	int dateMonthInt = Integer.parseInt(dateMonth);
    private int i;
    
    private JButton jButton1;
    
    private JLabel jLabel1;
    private JLabel jLabel3;
    
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JLabel lblTo;
    
    private JMenuBar menuBar;
    private JMenu overall;
    private JMenuItem back;
    private JMenuItem exit;
    
    @SuppressWarnings("rawtypes")
	private JComboBox comboBoxThang;
    @SuppressWarnings("rawtypes")
	private JComboBox comboBoxNam;
}
