package GUI;

import javax.swing.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.SimpleDateFormat;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author PC PV
 */
public class Luong extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form NewJFrame
     */
    public Luong() {
		setTitle("Th\u00F4ng tin l\u01B0\u01A1ng");
        initComponents();
        setLocationRelativeTo(null);
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    @SuppressWarnings({ "rawtypes", "unchecked" })
	private void initComponents() {
//        ImageIcon image = new ImageIcon(ClassLoader.getSystemResource("icons/icons/Hotel_Icon.png"));
//        setIconImage(image.getImage());
    	setVisible(true);
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelNamBep = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 11));

    

        jPanel1.setBackground(new java.awt.Color(36, 140, 165));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("TH\u00D4NG TIN L\u01AF\u01A0NG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Th\u1EDDi gian t\u00EDnh l\u01B0\u01A1ng"));

        jLabelNamBep.setFont(new Font("Tahoma", Font.PLAIN, 11)); // NOI18N
        jLabelNamBep.setText("N\u0103m");

        jButton1.setText("Xem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        overall = new JMenu("TU\u1EF2 CH\u1ECCN");
        overall.setForeground(Color.BLUE);
        menuBar.add(overall);
        
        back = new JMenuItem("QUAY V\u1EC0 TRANG CH\u1EE6");
        overall.add(back);
        back.setForeground(Color.BLUE);
        back.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
               	new TrangChu();
               	dispose();
            }
        });
        
        exit = new JMenuItem("THO\u00C1T H\u1EC6 TH\u1ED0NG");
        overall.add(exit);
        exit.setForeground(Color.RED);
        exit.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
               	System.exit(0);
            }
        });
        
         jLabelThangBep = new JLabel("Th\u00E1ng");
         jLabelThangBep.setFont(new Font("Tahoma", Font.PLAIN, 11));

         
        comboBoxBepNam = new JComboBox();
        
        comboBoxBepThang = new JComboBox();
        
        String[] choiceNam = {"2001", "2022"};
        comboBoxBepNam = new JComboBox(choiceNam);  
        for (i =0 ; i<choiceNam.length ; i++) {
        	if(Integer.parseInt(choiceNam[i]) == dateYearInt) {
        		break;
        	}
        }
        comboBoxBepNam.setSelectedIndex(i);
        
        String[] choiceThang = {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"};
        comboBoxBepThang = new JComboBox(choiceThang);
        
        for (i =0 ; i<choiceThang.length ; i++) {
        	if(Integer.parseInt(choiceThang[i]) == dateMonthInt) {
        		break;
        	}
        }
        comboBoxBepThang.setSelectedIndex(i);
        
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelThangBep, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelNamBep, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton1))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGap(22)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(comboBoxBepThang, 0, 106, Short.MAX_VALUE)
        						.addComponent(comboBoxBepNam, 0, 96, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelNamBep)
        				.addComponent(comboBoxBepNam, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelThangBep)
        				.addComponent(comboBoxBepThang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
        			.addComponent(jButton1))
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(306)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(60)
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(70))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(ActionEvent evt) {

    	try {
    		
    	
        String a = (String)(comboBoxBepNam.getSelectedItem());
        String b = (String)(comboBoxBepThang.getSelectedItem());
        
        if (a.equals("") || b.equals("")) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng m\u1EDF \u0111\u01B0\u1EE3c b\u1EA3ng l\u01B0\u01A1ng");
        }
        else {

        	if (a.equals(dateYear) && b.equals(dateMonth)) {
            	JOptionPane.showMessageDialog(null, "Ch\u01B0a h\u1EBFt th\u00E1ng n\u00EAn th\u00F4ng tin l\u01B0\u01A1ng ch\u01B0a ph\u1EA3i cu\u1ED1i c\u00F9ng");
        	}
        	int dateYearInt = Integer.parseInt(dateYear);
        	int dateMonthInt = Integer.parseInt(dateMonth);
        	int aInt = Integer.parseInt(a);
        	int bInt = Integer.parseInt(b);
        	
        	if((dateYearInt < aInt) || (dateMonthInt < bInt)) {
            	JOptionPane.showMessageDialog(null, "Ch\u01B0a t\u1EDBi th\u00E1ng l\u01B0\u01A1ng n\u00E0y");
        	}
        	else {
        	
        	
        LuongNV nvbep = new LuongNV(a,b);
        nvbep.setVisible(true);
        nvbep.pack();
        nvbep.setLocationRelativeTo(null);
        nvbep.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    	}
    	}
    	}
    	catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng m\u1EDF \u0111\u01B0\u1EE3c b\u1EA3ng l\u01B0\u01A1ng");
            ex.printStackTrace();
    	}
      
    }



	/**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                  
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Luong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Luong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Luong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Luong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Luong().setVisible(true);
//        		
//
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	SimpleDateFormat formatterYear= new SimpleDateFormat("yyyy");
	SimpleDateFormat formatterMonth= new SimpleDateFormat("MM");
	Date date = new Date(System.currentTimeMillis());
	String dateYear = formatterYear.format(date);
	String dateMonth = formatterMonth.format(date);
	int dateYearInt = Integer.parseInt(dateYear);
	int dateMonthInt = Integer.parseInt(dateMonth);
	
	
	
	private int i;
    private JButton jButton1;
    
    private JLabel jLabelNamBep;
    private JLabel jLabel3;
    
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JLabel jLabelThangBep;
    
    private JMenuBar menuBar;
    private JMenu overall;
    private JMenuItem back;
    private JMenuItem exit;

	@SuppressWarnings("rawtypes")
	private JComboBox comboBoxBepNam;

	@SuppressWarnings("rawtypes")
	private JComboBox comboBoxBepThang;
}
