package GUI;

import static Classes.MyConnection.getConnection;

import java.awt.Color;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import Classes.ChamCong;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.awt.Font;

public class QuanLyChamCong extends JFrame {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public QuanLyChamCong(String nam1, String thang1) {
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		
        initComponents(nam1,thang1);
        hienThiDanhSachChamCong(nam1,thang1);
        setLocationRelativeTo(null);
    }
	
    Connection con=null;
    Statement st=null;
    
    ChamCong nhanvien =new ChamCong();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    @SuppressWarnings({ "unchecked", "rawtypes" })
	private void initComponents(String nam1, String thang1) {
    	setVisible(true);

    	nam = String.valueOf(nam1);
    	thang = String.valueOf(thang1);
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelHoTen = new javax.swing.JLabel();
        jTextFieldHoTen = new javax.swing.JTextField();
        jTextFieldSoNgayNghi = new javax.swing.JTextField();
        them = new javax.swing.JButton();
        them.setFont(new Font("Tahoma", Font.BOLD, 10));
        sua = new javax.swing.JButton();
        sua.setFont(new Font("Tahoma", Font.BOLD, 10));
        xoa = new javax.swing.JButton();
        xoa.setFont(new Font("Tahoma", Font.BOLD, 10));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        clear = new JButton();
        clear.setFont(new Font("Tahoma", Font.BOLD, 10));

        setTitle("B\u1EA3ng ch\u1EA5m c\u00F4ng th\u00E1ng "+thang+" n\u0103m "+nam);
        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelHoTen.setText("T\u00EAn nh\u00E2n vi\u00EAn");


        them.setText("Th\u00EAm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them2ActionPerformed(evt);
            }
        });

        sua.setText("S\u1EEDa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua1ActionPerformed(evt);
            }
        });

        xoa.setText("Xo\u00E1");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa1ActionPerformed(evt);
            }
        });

        clear.setText("L\u00E0m m\u1EDBi");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        

        
        
        nghi = new JButton();
        nghi.setFont(new Font("Tahoma", Font.BOLD, 10));
        nghi.setForeground(Color.RED);
        nghi.addActionListener(new ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		xacNhanNghiActionPerformed(evt);
        	}
        	
        });
        
        
        batDauDiLam = new JButton();
        batDauDiLam.setFont(new Font("Tahoma", Font.BOLD, 10));
        batDauDiLam.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		dongBoNgayDiLamActionPerformed(evt);
        	}
        });
        
        nghi.setText("X\u00E1c nh\u1EADn h\u00F4m nay ngh\u1EC9");
        
        
        menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        overall = new JMenu("TU\u1EF2 CH\u1ECCN");
        overall.setForeground(Color.BLUE);
        menuBar.add(overall);
        
        qlnv = new JMenuItem("QU\u1EA2N L\u00DD NH\u00C2N VI\u00CAN");
        overall.add(qlnv);
        qlnv.setForeground(Color.GREEN);
        qlnv.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
               	new QuanLyNhanVien();
               	
            }
        });
        
        
        back = new JMenuItem("QUAY V\u1EC0 TRANG CH\u1EE6");
        overall.add(back);
        back.setForeground(Color.BLUE);
        back.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
               	new TrangChu();
               	dispose();
            }
        });
        
        
        exit = new JMenuItem("THO\u00C1T H\u1EC6 TH\u1ED0NG");
        overall.add(exit);
        exit.setForeground(Color.RED);
        exit.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
               	System.exit(0);
            }
        });
        
        jLabelSoNgayNghi = new JLabel("S\u1ED1 ng\u00E0y ngh\u1EC9");
        String[] choiceLuong = {"", "0.0","1.0", "2.0", "3.0"};
        String[] choiceNV = {"", "Nh\u00E2n vi\u00EAn b\u00E0n", "Nh\u00E2n vi\u00EAn b\u1EBFp"};
        comboBoxLoaiNhanVien = new JComboBox(choiceNV);
        
        comboBoxHeSoLuong = new JComboBox(choiceLuong);
        
        jLabelLoaiNhanVien = new JLabel("Lo\u1EA1i nh\u00E2n vi\u00EAn");
       
        jTextFieldSoNgayNghi.setText("0");
        
        jLabelGhiChu = new JLabel("Ghi ch\u00FA ng\u00E0y ngh\u1EC9");
        
        
        jTextFieldGhiChuNgayNghi = new JTextField();
        jTextFieldGhiChuNgayNghi.setColumns(10);
        jTextFieldGhiChuNgayNghi.setText("0");
        jLabelMaNhanVien = new JLabel("M\u00E3 nh\u00E2n vi\u00EAn");
        
        jTextFieldMaNV = new JTextField();
        jTextFieldMaNV.setColumns(10);
        
        jLabelHeSoLuong = new JLabel("H\u1EC7 s\u1ED1 l\u01B0\u01A1ng");
        
        comboBoxLoaiNhanVien.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Object selected = comboBoxLoaiNhanVien.getSelectedItem();
        		if(selected.toString().equals("Nh\u00E2n vi\u00EAn b\u00E0n")) {
        			comboBoxHeSoLuong.setSelectedItem("0.0");
        			comboBoxHeSoLuong.setEnabled(false);
        		}
        		else
        			comboBoxHeSoLuong.setEnabled(true);
        		
        	}
        });
        

        batDauDiLam.setText("\u0110\u1ED3ng b\u1ED9 ng\u00E0y b\u1EAFt \u0111\u1EA7u l\u00E0m");
        batDauDiLam.setForeground(Color.RED);
        


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabelSoNgayNghi, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabelMaNhanVien, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabelHoTen, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabelLoaiNhanVien, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabelGhiChu, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabelHeSoLuong, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
        					.addGap(272)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(comboBoxHeSoLuong, Alignment.TRAILING, 0, 260, Short.MAX_VALUE)
        						.addComponent(jTextFieldGhiChuNgayNghi, GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        						.addComponent(comboBoxLoaiNhanVien, 0, 260, Short.MAX_VALUE)
        						.addComponent(jTextFieldHoTen, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        						.addComponent(jTextFieldMaNV, GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        						.addComponent(jTextFieldSoNgayNghi, GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(them, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        						.addComponent(nghi, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
        					.addGap(92)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(sua, GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        							.addGap(14))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(batDauDiLam, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        							.addGap(15)))
        					.addGap(66)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(xoa, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        						.addComponent(clear, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(46)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelMaNhanVien, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextFieldMaNV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(29)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelHoTen, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextFieldHoTen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(29)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelLoaiNhanVien, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        				.addComponent(comboBoxLoaiNhanVien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(29)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelHeSoLuong, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        				.addComponent(comboBoxHeSoLuong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(30)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabelSoNgayNghi, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextFieldSoNgayNghi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(38)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelGhiChu, GroupLayout.PREFERRED_SIZE, 11, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextFieldGhiChuNgayNghi, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        			.addGap(51)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(them, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        				.addComponent(xoa, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        				.addComponent(sua, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(nghi, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        					.addComponent(clear, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
        				.addComponent(batDauDiLam, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
        			.addGap(29))
        );
        jPanel2.setLayout(jPanel2Layout);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        
        jLabelThang = new JLabel();
        jLabelThang.setText("th\u00E1ng "+ thang + " n\u0103m "+ nam);
        jLabelThang.setFont(new Font("Tahoma", Font.PLAIN, 24));
        jLabelThang.setBackground(Color.CYAN);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        			.addContainerGap(125, Short.MAX_VALUE)
        			.addComponent(jLabelThang, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
        			.addGap(124))
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabelThang, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4.setLayout(jPanel4Layout);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(41)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jPanel4, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
        				.addComponent(jPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(40)
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jScrollPane1, Alignment.LEADING)
        				.addComponent(jPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(61))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    private void clearActionPerformed(ActionEvent evt) {
        emptyField();
    }
    
    private void dongBoNgayDiLamActionPerformed(ActionEvent evt) {
    	Connection con = getConnection();
        try {
            st = (Statement) con.createStatement();
            String query = "select TIMESTAMPDIFF(MONTH,nhanvien.ngayDiLam,CURRENT_DATE()) from nhanvien where maNV = '" +
            		jTextFieldMaNV.getText()				+"'";
            ResultSet rs = st.executeQuery(query);
            String dongBoString = null;
            if(rs.next())
                dongBoString = rs.getString(1);
            int dongBoInt = Integer.parseInt(dongBoString);
            
            if (dongBoInt >0 || dongBoInt <0) {
            	JOptionPane.showMessageDialog(null, "Nh\u00E2n vi\u00EAn n\u00E0y \u0111\u00E3 \u0111i l\u00E0m t\u1EEB c\u00E1c th\u00E1ng tr\u01B0\u1EDBc");
            }
            else {
            	query = "select TIMESTAMPDIFF(DAY,nhanvien.ngayDiLam,CURRENT_DATE()) from nhanvien where maNV = '" +
                		jTextFieldMaNV.getText()				+"'";
            	rs = st.executeQuery(query);
                if(rs.next())
                    dongBoString = rs.getString(1);
                dongBoInt = Integer.parseInt(dongBoString);
                String note = "ng\u00E0y do b\u00E2y gi\u1EDD m\u1EDBi \u0111i l\u00E0m";
            	String noteFinal=(new StringBuilder()).append(dongBoString).append(" ").append(note).toString();

                String updateQuery = "update chamcong"+nam+thang+	" set maNV = '" 		+
                        jTextFieldMaNV.getText()				+"',"		+" hoTen = '"			+
                        jTextFieldHoTen.getText()				+"',"	 	+" loaiNhanVien = '" 	+
                        comboBoxLoaiNhanVien.getSelectedItem()	+"',"	 	+" heSoLuong = '" 		+	
                        comboBoxHeSoLuong.getSelectedItem()		+"',"	 	+" soNgayNghi = '" 		+
                        dongBoInt								+"',"       +" ghiChu = '" 			+       		
                        noteFinal								+"' where maNV= '" 					+
                        jTextFieldMaNV.getText()				+"'";
                st.execute(updateQuery);
                JOptionPane.showMessageDialog(null, "\u0110\u1ED3ng b\u1ED9 ho\u00E0n t\u1EA5t");
            }
            hienThiDanhSachChamCong(nam,thang);
            
           

        } catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng th\u00EAm \u0111\u01B0\u1EE3c nh\u00E2n vi\u00EAn");
            ex.printStackTrace();
        }

    }
    
    
    private void xacNhanNghiActionPerformed(ActionEvent evt) {
    	Connection con = getConnection();
        try {
        	
        	String soNgayNghiString = jTextFieldSoNgayNghi.getText();
        	int soNgayNghiInt = Integer.parseInt(soNgayNghiString);
        	soNgayNghiInt++;
        	String chiTietNgayNghiBefore = jTextFieldGhiChuNgayNghi.getText();
        	
        	String chiTietNgayNghi = jTextFieldGhiChuNgayNghi.getText();
        	if(chiTietNgayNghi.contains(dateString)) {
        		JOptionPane.showMessageDialog(null, "Kh\u00F4ng s\u1EEDa \u0111\u01B0\u1EE3c do h\u00F4m nay nh\u00E2n vi\u00EAn \u0111\u00E3 ngh\u1EC9 r\u1ED3i");
        	}
        	else {
        	
            	String chiTietNgayNghiAfter=(new StringBuilder()).append(chiTietNgayNghiBefore).append("+").append(dateString2).toString();

        		
            st = (Statement) con.createStatement();
            String updateQuery = "update chamcong"+nam+thang+	" set maNV = '" 		+
            jTextFieldMaNV.getText()				+"',"		+" hoTen = '"			+
            jTextFieldHoTen.getText()				+"',"	 	+" loaiNhanVien = '" 	+
            comboBoxLoaiNhanVien.getSelectedItem()	+"',"	 	+" heSoLuong = '" 		+	
            comboBoxHeSoLuong.getSelectedItem()		+"',"	 	+" soNgayNghi = '" 		+
            soNgayNghiInt							+"',"       +" ghiChu = '" 			+       		
            chiTietNgayNghiAfter					+"' where maNV= '" 					+
            jTextFieldMaNV.getText()				+"'";
            st.execute(updateQuery);
            hienThiDanhSachChamCong(nam,thang);
            
            JOptionPane.showMessageDialog(null, "\u0110\u00E3 ghi nh\u1EADn h\u00F4m nay ngh\u1EC9");
        	}
        } catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng s\u1EEDa \u0111\u01B0\u1EE3c th\u00F4ng tin nh\u00E2n vi\u00EAn");
            ex.printStackTrace();
        }
    }
    
    private void them2ActionPerformed(java.awt.event.ActionEvent evt) {
        
        String soNgayNghiString = jTextFieldSoNgayNghi.getText();
        int soNgayNghiInt = Integer.valueOf(soNgayNghiString);
        int ngayHienTaiInt = Integer.valueOf(dateString);
        
        if (soNgayNghiInt < 0 || soNgayNghiInt > ngayHienTaiInt) {
            JOptionPane.showMessageDialog(null, "S\u1ED1 ng\u00E0y ngh\u1EC9 kh\u00F4ng h\u1EE3p l\u1EC7");

        }
        else {
    	
        Connection con = getConnection();
        try {           
            st = (Statement) con.createStatement();
              
            String query = "INSERT into chamcong" +nam+thang+ "(maNV, hoTen, loaiNhanVien, heSoLuong, soNgayNghi ,ghiChu) VALUES ('"+ 
            		jTextFieldMaNV.getText()				+"','"+ 
            		jTextFieldHoTen.getText()				+"','"+ 
            		comboBoxLoaiNhanVien.getSelectedItem()	+"','"+
            		comboBoxHeSoLuong.getSelectedItem()		+"','"+
            		jTextFieldSoNgayNghi.getText()			+"','"+             		
            		jTextFieldGhiChuNgayNghi.getText()		+"')" ;
            st.execute(query);
            hienThiDanhSachChamCong(nam,thang);
            
            JOptionPane.showMessageDialog(null, "Th\u00EAm nh\u00E2n vi\u00EAn ho\u00E0n t\u1EA5t");
        
        } catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng th\u00EAm \u0111\u01B0\u1EE3c nh\u00E2n vi\u00EAn");
            ex.printStackTrace();
        }
        }

    }

    private void sua1ActionPerformed(java.awt.event.ActionEvent evt) {
        Connection con = getConnection();
        
        String soNgayNghiString = jTextFieldSoNgayNghi.getText();
        int soNgayNghiInt = Integer.valueOf(soNgayNghiString);
        int ngayHienTaiInt = Integer.valueOf(dateString);
        
        if (soNgayNghiInt < 0 || soNgayNghiInt > ngayHienTaiInt) {
            JOptionPane.showMessageDialog(null, "S\u1ED1 ng\u00E0y ngh\u1EC9 kh\u00F4ng h\u1EE3p l\u1EC7");

        }
        else {
        try {
            st = con.createStatement();
            String updateQuery = "update chamcong"+nam+thang+	" set maNV = '" 		+
            jTextFieldMaNV.getText()				+"',"		+" hoTen = '"			+
            jTextFieldHoTen.getText()				+"',"	 	+" loaiNhanVien = '" 	+
            comboBoxLoaiNhanVien.getSelectedItem()	+"',"	 	+" heSoLuong = '" 		+	
            comboBoxHeSoLuong.getSelectedItem()		+"',"	 	+" soNgayNghi = '" 		+	
            jTextFieldSoNgayNghi.getText() 			+"',"	 	+" ghiChu = '" 			+        
            jTextFieldGhiChuNgayNghi.getText() 		+"' where maNV= '" 					+
            jTextFieldMaNV.getText()				+"'";
            
            st.execute(updateQuery);
            hienThiDanhSachChamCong(nam,thang);
            
            JOptionPane.showMessageDialog(null, "S\u1EEDa th\u00F4ng tin ho\u00E0n t\u1EA5t");

        } catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng s\u1EEDa \u0111\u01B0\u1EE3c th\u00F4ng tin nh\u00E2n vi\u00EAn");
            ex.printStackTrace();
        }
        }
    }

    private void xoa1ActionPerformed(java.awt.event.ActionEvent evt) {

        Connection con = getConnection();
        try {
            st = con.createStatement();
            String query = "DELETE FROM chamcong"+nam+thang+" WHERE maNV = '" + jTextFieldMaNV.getText() + "'";
            st.executeUpdate(query);
            hienThiDanhSachChamCong(nam, thang);
            emptyField();

            JOptionPane.showMessageDialog(null, "Xo\u00E1 nh\u00E2n vi\u00EAn ho\u00E0n t\u1EA5t");
        } catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng xo\u00E1 \u0111\u01B0\u1EE3c nh\u00E2n vi\u00EAn");
            ex.printStackTrace();
        }

    }
    

    //CSDL
    public ArrayList<ChamCong> layDanhSachChamCong(String nam1, String thang1) {
        ArrayList<ChamCong> dsnv = new ArrayList<ChamCong>();
        Connection con = getConnection();
        String nam11 = String.valueOf(nam1);
        String thang11 = String.valueOf(thang1);
        
        try {
            st = con.createStatement();
            String sql = "SELECT * FROM chamcong"+nam11+thang11;
            ResultSet rs = st.executeQuery(sql);

            ChamCong cc;
            while (rs.next()) {
                cc = new ChamCong(rs.getString("maNV"), rs.getString("hoTen"), rs.getString("loaiNhanVien"), rs.getDouble("heSoLuong"),rs.getInt("soNgayNghi"), rs.getString("ghiChu"));

                dsnv.add(cc);
            }
        } catch (Exception ex) {
        	JOptionPane.showMessageDialog(null, "Kh\u00F4ng l\u1EA5y \u0111\u01B0\u1EE3c danh s\u00E1ch nh\u00E2n vi\u00EAn");
            ex.printStackTrace();

        }
        return dsnv;
    }
    //Hien thi CSDL
    public void hienThiDanhSachChamCong(String nam1, String thang1) {
        String colTieuDe1[] = new String[]{"M\u00E3 nh\u00E2n vi\u00EAn","T\u00EAn nh\u00E2n vi\u00EAn","Lo\u1EA1i nh\u00E2n vi\u00EAn","H\u1EC7 s\u1ED1 l\u01B0\u01A1ng", "S\u1ED1 ng\u00E0y ngh\u1EC9","Ghi ch\u00FA"};
        ArrayList<ChamCong> dnnv = layDanhSachChamCong(nam1, thang1);

        model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        
        for (int i = 0; i < dnnv.size(); i++) {

            row = new Object[6];
            
            row[0] = dnnv.get(i).getMaNV();
            row[1] = dnnv.get(i).getHoTen();
            row[2] = dnnv.get(i).getLoaiNhanVien();
            row[3] = dnnv.get(i).getHeSoLuong(); 
            row[4] = dnnv.get(i).getSoNgayNghi();
            row[5] = dnnv.get(i).getGhiChu();

            model.addRow(row);
        }
        jTable.setModel(model);
//        jTable.getColumnModel().getColumn(1).setPreferredWidth(150);
//        jTable.getColumnModel().getColumn(2).setPreferredWidth(100);
//        jTable.getColumnModel().getColumn(3).setPreferredWidth(150);
//        jTable.getColumnModel().getColumn(4).setPreferredWidth(60);
//        jTable.getColumnModel().getColumn(5).setPreferredWidth(120);


    }


    private void jTableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {
        int i = jTable.getSelectedRow();
        TableModel model = jTable.getModel();
        jTextFieldMaNV.setText(model.getValueAt(i, 0).toString());
        jTextFieldHoTen.setText(model.getValueAt(i, 1).toString());
        comboBoxLoaiNhanVien.setSelectedItem(model.getValueAt(i, 2).toString());
        comboBoxHeSoLuong.setSelectedItem(model.getValueAt(i, 3).toString());
        jTextFieldSoNgayNghi.setText(model.getValueAt(i, 4).toString());
        jTextFieldGhiChuNgayNghi.setText(model.getValueAt(i, 5).toString());
        them.setEnabled(false);
        sua.setEnabled(true);
        xoa.setEnabled(true);
    }

    private void emptyField()
    {
        them.setEnabled(true);
        sua.setEnabled(false);
        xoa.setEnabled(false);
        
        jTextFieldMaNV.setText("");
        jTextFieldHoTen.setText("");
        comboBoxLoaiNhanVien.setSelectedItem("");
        jTextFieldSoNgayNghi.setText("0");
        comboBoxHeSoLuong.setSelectedItem("");
        jTextFieldGhiChuNgayNghi.setText("0");
        jTable.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuanLyChamCong(nam1, thang1).setVisible(true);
//            }
//        });
//    }
    SimpleDateFormat formatter= new SimpleDateFormat("dd");
	Date date = new Date(System.currentTimeMillis());
	String dateString = formatter.format(date);
    SimpleDateFormat formatter2= new SimpleDateFormat("dd/MM");
	Date date2 = new Date(System.currentTimeMillis());
	String dateString2 = formatter2.format(date2);

    private JLabel jLabelHoTen;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel4;
    
    private JScrollPane jScrollPane1;
    private JTable jTable;
    private JTextField jTextFieldHoTen;
    private JTextField jTextFieldSoNgayNghi;
    
    private JButton clear;
    private JButton sua;
    private JButton them;
    private JButton xoa;
    
    private JLabel jLabelThang;
    private JLabel jLabelSoNgayNghi;
    private JLabel jLabelLoaiNhanVien;
    private JLabel jLabelHeSoLuong;
    @SuppressWarnings("rawtypes")
	private JComboBox comboBoxLoaiNhanVien;
    @SuppressWarnings("rawtypes")
	private JComboBox comboBoxHeSoLuong;
    private JLabel jLabelGhiChu;
    private JTextField jTextFieldGhiChuNgayNghi;
    
    private String nam;
    private String thang;
    private JLabel jLabelMaNhanVien;
    private JTextField jTextFieldMaNV;
    private JButton batDauDiLam;
    private JButton nghi;
    
    private JMenuBar menuBar;
    private JMenu overall;
    private JMenuItem back;
    private JMenuItem exit;
    private JMenuItem qlnv;
    
    private DefaultTableModel model;
}
